user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # 레거시 센서 디바이스가 큰 응답 바디를 못 다루는 구형 장비일 수 있어 기본값 유지, 필요 시 조정
    client_max_body_size 10m;

    include /etc/nginx/conf.d/*.conf;
}
